### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by asfaltboy** [facebook/codemod#111]
@modocache @rochacbruno @facebook anyone know the status of this project? Who has commit bit and can merge or discuss the open tickets/PRs? I'm considering to contribute to this repo and not sure whether I should or should I maintain a fork?

**Comment by rochacbruno** [comment]
Hi @asfaltboy I do not have rights anymore the only think I still own is the PyPI namespace to make releases.

**Comment by modocache** [comment]
It's maintained, but looking at the rate of commits I think it's safe to say it's not actively developed. https://github.com/facebookincubator/fastmod is a more active project.
