### ISSUE TITLE
auto git-add all changes

### ISSUE THREAD

**Issue by Dieterbe** [facebook/codemod#13]
i always find myself doing 2 loops over the edit locations.
once to make the edit, and then using `git add -p`, to add all changes to the git index. would be pretty convenient to automatically stage to the index all changes i make

**Comment by nylen** [comment]
@caabernathy @modocache why was this closed?

**Comment by caabernathy** [comment]
This happened when we (temporarily) stopped supporting this project. Support recently started up again.

**Comment by nylen** [comment]
Glad to see it!  :+1: for this feature, then.  If someone can provide an outline of a desired implementation, or a place to start, I can give it a shot.
