### ISSUE TITLE
Match all extensions / --extensions should accept glob arguments

### ISSUE THREAD

**Issue by jonhoo** [facebook/codemod#30]
I have a codebase in which I would like to search *all* files within a certain directory for matches. This directory also has several files without an extension (shell scripts). At the moment, there is no way of specifying this in codemod as far as I'm aware?

**Comment by modocache** [comment]
I think this sounds like a great change! It sounds like it would be possible to accomplish this by having `--extensions` accept glob arguments. Then you could include all files in `/path/to/dir` by writing:

```
$ codemod.py -d /path/to/dir --extensions * --include-extensionless
```

**Comment by jonhoo** [comment]
Yes, that would be perfect.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
