### ISSUE TITLE
Replace complete line (including newline) matches only every second line

### ISSUE THREAD

**Issue by david0** [facebook/codemod#33]
Hi,
I want to remove every line that matches a specific pattern completely (including newline).
I would expect that `[ \t]*require_once[^\n\r]*\r?\n?` would match every line that contains requrie_once.
In fact, only every second line is removed:

Testcase:

``` bash
$ cat codemodtest/A.php
<?php

require_once 'B.php';
require_once 'C.php';
require_once 'D.php';
require_once 'E.php';

class A {
}

?>


$ codemod.py -m -d codemodtest --extension php,inc '[ \t]*require_once[^\n\r]*\r?\n?' ''

$ cat codemodtest/A.php
<?php

require_once 'C.php';
require_once 'E.php';

class A {
}

?>
```

**Comment by modocache** [comment]
This sounds like a serious issue. Reopening in order to investigate.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
