### ISSUE TITLE
Cannot codemod extensionless files

### ISSUE THREAD

**Issue by grp** [facebook/codemod#37]
There's no way to specify extensionless files to codemod. This gets in the way of files used by some build systems, like BUILD or BUCK files.

**Comment by modocache** [comment]
Hmm, that seems like an oversight. Hopefully it'll be easy to fix.

Out of curiosity, what happens when you run `codemod.py --extensions BUCK`? #lazyweb

**Comment by grp** [comment]
Doesn't find anything, sadly.

**Comment by glenpike** [comment]
Fix isn't good enough - needs wild-card as I have 20+ extensionless files to fix.

**Comment by modocache** [comment]
@glenpike As far as I can tell, codemod doesn't currently support glob patterns like `*`. Feel free to open a separate issue for that feature, though!
