### ISSUE TITLE
Select default action

### ISSUE THREAD

**Issue by DanNixon** [facebook/codemod#50]
Currently the default action for ```Accept change``` is yes, when doing a change where you want to change only the minority of instances it would be good to be able to set the default to be no.

**Comment by modocache** [comment]
I agree, this would be nice to have! :flashlight:

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by asm89** [comment]
Merged #57 which adds a flag for this.
