### ISSUE TITLE
--include-extensionless has no effect

### ISSUE THREAD

**Issue by nickhutchinson** [facebook/codemod#59]
The `--include-extensionless` option appears to be broken: in `_parse_command_line()`, it's never forwarded the actual `Query` object.

**Comment by rochacbruno** [comment]
Fixed here: https://github.com/facebook/codemod/commit/86789e10e0ae2b236129620d2d9f139afa04d9c4

**Comment by modocache** [comment]
Thanks! Sorry for not closing this sooner.
