### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [facebook/codemod#61]
Hello,
Could you please tag a release here so we could include `codemod` in Homebrew core?
Thanks!

**Comment by modocache** [comment]
@bfontaine Oh wow, I had no idea that codemod was even in homebrew! That's really cool. :sunglasses: 

Still, I think the only installation method we're ready to support right now is via pip. This script has never had a tagged release, and no plans around versioning of any kind. I think the better approach here would be to please remove this script from homebrew.

If users would like codemod to be added to homebrew, we can think about versioning/tagging releases at that time, and then re-add it to homebrew.

Thanks! :100:

**Comment by kastiglione** [comment]
@bfontaine I've volunteered to tag releases so that codemod can be added to homebrew. First release is [20151117](https://github.com/facebook/codemod/releases/tag/20151117).

**Comment by modocache** [comment]
Thanks, @kastiglione! :+1:

**Comment by bfontaine** [comment]
Thank you both; `codemod` 20151117 is now in the core :smile:

**Comment by kastiglione** [comment]
:+1:
