### ISSUE TITLE
why not realease it to PyPI and make entry_points?

### ISSUE THREAD

**Issue by rochacbruno** [facebook/codemod#62]
Hi,

Currently it has to be installed from github source

Why not release it to PyPI and add console_scripts as entry point?

So it allows us to do

```
pip install codemod
codemod -m -d /home/jrosenstein/www --extensions php,html \
    '<font *color="?(.*?)"?>(.*?)</font>' \
    '<span style="color: \1;">\2</span>'
```

If any help  needed I can help packacking and releasing.

**Comment by modocache** [comment]
Absolutely!
