### ISSUE TITLE
[solved] Installing on Ubuntu [permission problem, use sudo]

### ISSUE THREAD

**Issue by omidfi** [facebook/codemod#72]
Hi this tool sounds so useful and I'm trying to install it,
 I don't speak Python, but usually I manage to install Python utilities on my Ubuntu. But seems like this is not the case. 
Is there anything needed after running 
   pip install codemod

To get it running in my terminal? 
I see the codemod folder created with some python files in it, should I add something to path to be able to run it? 
/home/omid/.local/lib/python2.7/site-packages/codemod

Thank you!

**Comment by rochacbruno** [comment]
@omidfi you should only do "sudo pip install codemod" in ubuntu and then run "codemod" command. if any issue found please report us.

**Comment by omidfi** [comment]
@rochacbruno thanks! seems like the problem was not using "sudo" 
I didn't use sudo to install, and it installed with no errors, but after using sudo it showed
```
The directory '/home/omid/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```
And after that 
  sudo -H pip install codemod

Was all needed to make it work!

**Comment by rochacbruno** [comment]
So we should add that info to README maybe
