### ISSUE TITLE
fork in modone

### ISSUE THREAD

**Issue by indigoviolet** [facebook/codemod#76]
Hey codemod folks-

just wanted to bring to your notice https://github.com/indigoviolet/modone, which is a fork of `codemod` but delegates all the filesystem traversal and filtering to unix utilities. I think it's probably too large of a behavioral change to attempt to bring upstream (hence the fork), but wanted to point it out anyway.

**Comment by modocache** [comment]
Awesome, thanks! Looks like a great project. We could mention it in the codemod README as an alternative implementation. If you think codemod users would be interested, send a pull request to add a blurb to our README, which would ideally explain why and why not to use modone instead.

Thanks for the heads up! :)
