### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by rouge8** [facebook/codemod#81]
Any chance of tagging and pushing a new release?

**Comment by modocache** [comment]
@kastiglione I think you did this before... :)

**Comment by modocache** [comment]
No wait, it was @rochacbruno :)

**Comment by rochacbruno** [comment]
@modocache I think I did it once

**Comment by rochacbruno** [comment]
BTW: @modocache looks like I lost my access to this org

**Comment by rochacbruno** [comment]
@modocache I sent you an email about getting access to repo again, So I can bump version and release to Pypi.

(also please tell me your PyPI username so I can add you there as maintainer look #66)

**Comment by modocache** [comment]
Replied to your email!

OK, no way around it -- I think I'll have to update PyPI this time. I'll also take care of #66 while I'm at it. Thanks, @rochacbruno!

**Comment by rouge8** [comment]
Anyone ever have any luck? :)

**Comment by rochacbruno** [comment]
@rouge8 @modocache the PyPI package is under my ownership and I want to add someone else as owner/maintainer. Please give me yourr PyPI username and I can do that, and then you can control the releases.

**Comment by keyan** [comment]
@modocache -- I know the new contributor guidelines don't allow for us to be collaborators, but if it is okay with you I am happy to take ownership for the PyPi package so I can update the release. One doesn't need repo access to update the package.

@rochacbruno my PyPi username is `keyanp`

**Comment by modocache** [comment]
Sounds fine to me! Yeah, a new release would be great.

**Comment by rochacbruno** [comment]
@keyan added https://pypi.python.org/pypi/codemod now you have permission to `python setup.py sdist upload`

**Comment by rochacbruno** [comment]
@keyan BTW you will need access to repo to bump the version. It would be better if @modocache releases, it is just a matter of bumping the version on `setup.py` and running `python setup.py sdist upload`

We can also setup travis CI to release to PyPI automatically when a tagged PR passes.

@modocache what is your PyPI username?

**Comment by modocache** [comment]
Should we revert the README to the instructions that had users install via pip install `git+https://github.com/facebook/codemod.git`? It seems like that would be easier than coordinating PyPI releases. As far as I can tell, it just adds overhead...? Please correct me if I'm wrong.

My PyPI username is `B.G`. I wish I could change it...

**Comment by keyan** [comment]
> @keyan BTW you will need access to repo to bump the version.

For now I just opened a PR to bump the version. The only thing I can't do without access is make a new github tag.

> We can also setup travis CI to release to PyPI automatically when a tagged PR passes.

Reading through https://docs.travis-ci.com/user/deployment/pypi/ it seems to me that we would have to tag a commit so I'd still need write access to the repo.

> Should we revert the README to the instructions that had users install via pip install git+https://github.com/facebook/codemod.git? It seems like that would be easier than coordinating PyPI releases. As far as I can tell, it just adds overhead...? Please correct me if I'm wrong.

I'm personally in favor of keeping the PyPI releases because it is easier to install/manage packages this way than manually installing the repo. It does add some overhead, but I'm fine maintaining for now at least.

**Comment by rouge8** [comment]
@modocache @keyan I don't actually see the new release on PyPI?

**Comment by keyan** [comment]
Hey @rouge8 -- that was because my PR wasn't merged until the weekend and I was offline :)

Uploaded it just a few minutes ago!
